# rename config.yaml and replace with your bot token 
token: 'YOUR_TOKEN_HERE'
# add your tasks to array
tasks: 
    #number is the weight, ex, 10 is 10x more likely to shop up than 1
    4: ["Common Example"]
    3: ["Frequent Example"]
    2: ["Infrequent Example"]
    1: ["Rare Example"]